# Generated by Django 3.0.3 on 2020-07-01 14:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_auto_20200630_0554'),
        ('groups', '0007_auto_20200308_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PhotoMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('caption', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('u_id', models.CharField(default='replace', max_length=20)),
                ('post_type', models.IntegerField(verbose_name=[(0, 'Photo'), (1, 'Link'), (2, 'Text')])),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_posts', to='groups.Group')),
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.LinkMedia')),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.PhotoMedia')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='my_posts', to='users.Profile')),
            ],
        ),
    ]
