# Generated by Django 3.0.3 on 2020-06-30 05:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0007_auto_20200308_0955'),
        ('users', '0006_auto_20200630_0554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(max_length=20)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('post_type', models.IntegerField(verbose_name=[(0, 'Photo'), (1, 'Link'), (2, 'Text')])),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_posts', to='groups.Group')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='my_posts', to='users.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoPost',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.Media')),
                ('url', models.URLField()),
                ('caption', models.TextField()),
            ],
            bases=('posts.media',),
        ),
    ]
