# Generated by Django 3.0.3 on 2020-07-01 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200701_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.LinkMedia'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.PhotoMedia'),
        ),
    ]
