# Generated by Django 3.0.3 on 2020-04-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='Full Name', max_length=70),
        ),
    ]
