# Generated by Django 3.0.3 on 2020-08-04 11:41

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200630_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='feed',
            field=django_mysql.models.ListTextField(models.CharField(max_length=20), blank=True, null=True, size=None),
        ),
    ]
