# Generated by Django 3.0.3 on 2020-03-08 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_friends'),
        ('groups', '0003_auto_20200308_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='users.Profile'),
        ),
    ]
