# Generated by Django 3.0.3 on 2020-03-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_friends'),
        ('groups', '0005_group_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='members', to='users.Profile'),
        ),
    ]
