# Generated by Django 3.0.7 on 2020-11-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_auto_20200308_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='banner',
            field=models.URLField(blank=True),
        ),
    ]
